version: '2.2'
services:
  localstack:
    container_name: "LocalStack-Demo"
    image: localstack/localstack
    network_mode: bridge
    ports:
      - "4566:4566"
    environment:
      - DEFAULT_REGION=us-east-1
      - SERVICES=s3
      - EDGE_PORT=4566
      - DEBUG=1 # Debug level 1 if you want to logs, 0 if you want to disable
      - AWS_ACCESS_KEY_ID=localstack
      - AWS_SECRET_ACCESS_KEY=localstack
      - AWS_DEFAULT_REGION=us-east-1
    volumes:
      - './.localstack:/tmp/localstack'
      - '/var/run/docker.sock:/var/run/docker.sock'
