# API
server:
  port: 8082

spring:
  # Datasource
  datasource:
    url: jdbc:mysql://localhost:3306/resource
    username: sa
    password: .......
  # Enable multipart uploads
  servlet:
    multipart:
      enabled: true
      max-file-size: 200MB
      max-request-size: 215MB
  # RabbitMQ
  rabbitmq:
    host: localhost
    port: 15672
    username: guest
    password: guest
    exchange: user.exchange
    routingkey: user.routingkey
  # Stub runner
  output:
    ansi:
      enabled: 'ALWAYS'
  main:
    allow-bean-definition-overriding: true


stubrunner:
  amqp:
    enabled: true

# Localstack
aws:
  region: us-east-1
  s3:
    url: http://localhost:4566
    bucket-name: music-bucket