# API
server:
  port: 8082
  tomcat:
    max-http-form-post-size: -1  # infinite
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_SERVER}

spring:
  application:
    name: resourceservice
  datasource:
    url: ${DATASOURCE_DATABASE_URL}
    driverClassName: com.mysql.cj.jdbc.Driver
    username: ${DATASOURCE_USERNAME}
    password: ${DATASOURCE_PASSWORD}
  # Enable multipart uploads
  servlet:
    multipart:
      enabled: true
      max-file-size: -1
      max-request-size: -1
  # RabbitMQ
  rabbitmq:
    host: ${RABBIT_MQ_HOST}
    port: ${RABBIT_MQ_PORT}
    username: ${RABBIT_MQ_USERNAME}
    password: ${RABBIT_MQ_PASSWORD}
    exchange: ${RABBIT_MQ_PASSWORD}
    routingkey: ${RABBIT_MQ_ROUTING_KEY}
  # Stub runner
  output:
    ansi:
      enabled: 'ALWAYS'
  main:
    allow-bean-definition-overriding: true

stubrunner:
  amqp:
    enabled: true

# Localstack
aws:
  region: ${AWS_REGION}
  use-default-aws-region-chain: true
  s3:
    url: ${AWS_S3_URL}
    bucket-name: ${AWS_S3_BUCKET_NAME}
logging:
  level:
    com:
      amazonaws:
        util:
          EC2MetadataUtils: error
        internal:
          InstanceMetadataServiceResourceFetcher: error

# Synchronized Communication
webclient:
  songservice:
    endpoint: ${WEBCLIENT_SONG_SERVICE_ENDPOINT}
  resourceservice:
    endpoint: ${WEBCLIENT_RESOURCE_SERVICE_ENDPOINT}