# API
server.port: 8083

# RabbitMQ
spring:
  rabbitmq:
    host: localhost
    port: 15672
    username: guest
    password: guest
    exchange: user.exchange
    queue: user.queue # queue name that we consume messages from
    routingkey: user.routingkey