# API
server:
  port: 8083

# RabbitMQ
spring:
  rabbitmq:
    host: ${RABBIT_MQ_HOST}
    port: ${RABBIT_MQ_PORT}
    username: ${RABBIT_MQ_USERNAME}
    password: ${RABBIT_MQ_PASSWORD}
    exchange: ${RABBIT_MQ_PASSWORD}
    queue: ${RABBIT_MQ_QUEUE} # queue name that we consume messages from
    routingkey: ${RABBIT_MQ_ROUTING_KEY}
  # stub runner
  output:
    ansi:
      enabled: 'ALWAYS'

stubrunner:
  work-offline: true
#  ids: 'com.epam.msa:resourceservice'
  amqp:
    enabled: true

# Synchronized Communication
webclient:
  songservice:
    url: ${WEBCLIENT_SONG_SERVICE_URL}
  resourceservice:
    url: ${WEBCLIENT_RESOURCE_SERVICE_URL}