# API
server:
  port: 8083
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_SERVER}

spring:
  application:
    name: resourceprocessor
# RabbitMQ
  rabbitmq:
    host: ${RABBIT_MQ_HOST}
    port: ${RABBIT_MQ_PORT}
    username: ${RABBIT_MQ_USERNAME}
    password: ${RABBIT_MQ_PASSWORD}
    exchange: ${RABBIT_MQ_PASSWORD}
    queue: ${RABBIT_MQ_QUEUE} # queue name that we consume messages from
    routingkey: ${RABBIT_MQ_ROUTING_KEY}
  # stub runner
  output:
    ansi:
      enabled: 'ALWAYS'

stubrunner:
  work-offline: true
  amqp:
    enabled: true