# API
server.port: 8083

# Localstack
aws:
  region: us-east-1
  s3:
    url: http://localhost:4566
    bucket-name: music-bucket

# RabbitMQ
spring:
  rabbitmq:
    host: localhost
    port: 15672
    username: guest
    password: guest
    exchange: user.exchange
    queue: user.queue # queue name that we consume messages from
    routingkey: user.routingkey

# Synchronized Communication
webclient:
  songservice.url: http://localhost:8081