# API
server:
  port: 8083

# RabbitMQ
spring:
  rabbitmq:
    host: localhost
    port: 15672
    username: guest
    password: guest
    exchange: user.exchange
    queue: user.queue # queue name that we consume messages from
    routingkey: user.routingkey
  # stub runner
  output:
    ansi:
      enabled: 'ALWAYS'

stubrunner:
  work-offline: true
#  ids: 'com.epam.msa:resourceservice'
  amqp:
    enabled: true

# Synchronized Communication
webclient:
  songservice:
    url: http://localhost:8081
  resourceservice:
    url: http://localhost:8082