# API
server:
  port: 8081

# Datasource
spring:
  datasource:
    url: ${DATASOURCE_DATABASE_URL}
    driverClassName: com.mysql.cj.jdbc.Driver
    username: ${DATASOURCE_USERNAME}
    password: ${DATASOURCE_PASSWORD}