# API
server:
  port: 8081
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_SERVER}

spring:
  application:
    name: songservice
  # Datasource
  datasource:
    url: ${DATASOURCE_DATABASE_URL}
    driverClassName: com.mysql.cj.jdbc.Driver
    username: ${DATASOURCE_USERNAME}
    password: ${DATASOURCE_PASSWORD}